---
title: "Tarea_diplomado_Paula"
author: "Paula Celis Plá"
date: "2022-09-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Summary

```{r cars}
summary(cars)
```

## Variables categorias Seasonal, time, hours  y replicate asigna factor  

```{r}
Datos_Proyecto <- read_excel("Datos_Proyecto.xlsx")
summary(Datos_Proyecto)

```

## Transforma variables a factores

```{r}
Datos_Proyecto$Seasons <- as.factor(Datos_Proyecto$Seasons)
Datos_Proyecto$time <- as.factor(Datos_Proyecto$time)
Datos_Proyecto$hours <- as.factor(Datos_Proyecto$hours)
Datos_Proyecto$Replicate <- as.factor(Datos_Proyecto$Replicate)
summary(Datos_Proyecto)
```

## Including Plots

```{r}
library(stats)
library(graphics)
library(psych)
library(readxl)
library(agridat)
library(ggplot2)
```

# Histogramas

```{r}
ggplot(Datos_Proyecto, aes(Chla)) + geom_histogram()
ggplot(Datos_Proyecto, aes(Chlc)) + geom_histogram()
ggplot(Datos_Proyecto, aes(Car)) + geom_histogram()
ggplot(Datos_Proyecto, aes(PC)) + geom_histogram()
ggplot(Datos_Proyecto, aes(DPPH)) + geom_histogram()
ggplot(Datos_Proyecto, aes(C)) + geom_histogram()
ggplot(Datos_Proyecto, aes(N)) + geom_histogram()
ggplot(Datos_Proyecto, aes(Ratio)) + geom_histogram()
ggplot(Datos_Proyecto, aes(Nitrato)) + geom_histogram()
ggplot(Datos_Proyecto, aes(Fosfato)) + geom_histogram()
ggplot(Datos_Proyecto, aes(Temperature)) + geom_histogram()
ggplot(Datos_Proyecto, aes(pH)) + geom_histogram()
ggplot(Datos_Proyecto, aes(Salinity)) + geom_histogram()
ggplot(Datos_Proyecto, aes(PAR)) + geom_histogram()
ggplot(Datos_Proyecto, aes(UVA)) + geom_histogram()
ggplot(Datos_Proyecto, aes(UVB)) + geom_histogram()
```


You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
